apiVersion: v1
kind: ConfigMap
metadata:
  name: kubecube-language-config
  namespace: kubecube-system
data:
  languages: "zh,en"
  en.toml: |
    # method
    POST = "create"
    PUT = "update"
    DELETE = "delete"

    # resourceType
    deployments = "Deployment"
    namespaces = "Namespace"
    jobs = "Job"
    cronjobs = "Cronjob"
    persistentvolumeclaims = "Persistentvolumeclaim"
    customresourcedefinitions = "Customresourcedefinition"
    horizontalpodautoscalers = "Horizontalpodautoscaler"
    networkpolicies = "Networkpolicie"
    statefulsets = "Statefulset"
    replicasets = "Replicaset"
    pods = "Pod"
    secrets = "Secret"
    ingresses = "Ingress"
    services = "Service"
    configmaps = "Configmap"
    user = "User"
    key = "Key"

    # description
    createUser = "createUser"
    updateUser = "updateUser"
    deleteKey = "deleteKey"

  zh.toml: |
    # method
    POST = "创建"
    PUT = "更新"
    DELETE = "删除"

    # resourceType
    deployments = "无状态负载"
    namespaces = "namespace"
    jobs = "任务"
    cronjobs = "定时任务"
    persistentvolumeclaims = "存储声明"
    customresourcedefinitions = "自定义资源"
    horizontalpodautoscalers = "自动伸缩(HPA)"
    networkpolicies = "网络策略"
    statefulsets = "有状态负载"
    replicasets = "副本集"
    pods = "副本"
    secret = "secret"
    ingresses = "ingress"
    services = "service"
    configmaps = "configmap"
    user = "user"
    key = "key"

    # description
    createUser = "创建用户"
    updateUser = "更新用户"
    deleteKey = "删除密钥"