apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubecube-ingress
  namespace: kubecube-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "cube.kubecube.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubecube
                port:
                  number: 7777